<ips:template parameters="$table" />
<div class='ipsPad ipsBox ipsSpacer_bottom'>
	<span class='ipsType_bold ipsType_large'>Códigos de colores para los anuncios:</span><br>
	<span>Estos códigos sirven para cambiar el color en algunas partes del texto en los anuncios que aparecerán dentro de los servidores de juego.</span>

	<ul type='none'>
		<li><i class='fa fa-check'></i> <span class='ipsType_bold' style='color: green;'>!g</span> = Color verde</li>
		<li><i class='fa fa-check'></i> <span class='ipsType_bold' style='color: orange;'>!y</span> = Color por defecto del cliente</li>
		<li><i class='fa fa-check'></i> <span class='ipsType_bold' style='color: gray;'>!t</span> = Color de equipo (<span class='ipsType_bold' style='color: red;'>T</span> / <span class='ipsType_bold' style='color: #00bbaa'>CT</span> / <span class='ipsType_bold' style='color: gray;'>Spect</span>)</li>
	</ul>
</div>

<div class='ipsBox'>{$table|raw}</div>