<ips:template parameters="$data" />
{{if !\IPS\Request::i()->isAjax()}}
	<div class='ipsPageHeader ipsPadding ipsBox ipsClearfix ipsMargin_bottom cVentas_header'>
		<h1 class='ipsType_pageTitle'>{lang="module__ventas_main"}</h1>
	</div>
{{endif}}

{{if !$data['zpa_check_vinc']}}
	<div class='ipsPadding {{if !\IPS\Request::i()->isAjax()}}ipsBox{{endif}}'>
		<div class='ipsMessage ipsMessage_info'>
			Debes tener la cuenta del ZP Annihilation vinculada al foro para poder realizar una compra. Para vincular tu cuenta del ZP Annihilation con la del foro, debes ingresar al servidor de juego, e ir a la Opción <strong>Vincular mi cuenta</strong> que aparecerá tanto en el menú de Ingreso como en el menú de Opciones de Usuario.
		</div>

		<hr class='ipsHr' />

		{template="zpaInformation" app="ventas" group="zpa" location="front"}
	</div>
{{else}}
	<div class='ipsGrid ipsGrid_collapsePhone ipsPad {{if !\IPS\Request::i()->isAjax()}}ipsBox{{endif}}'>
		<div class='ipsGrid_span4 ipsPad ipsAreaBackground_light ipsSpacer_bottom'>
			{$data['zpa_form']|raw}

			{{if $data['percent_extra']}}
				<div class='ipsMessage ipsMessage_success ipsSpacer_top'>
					Todos los puntos adquiridos <strong>sumarán un {$data['percent_extra']}% extra</strong>. Por ejemplo: Si compras <strong>1.000 pH, sabiendo que hay un 50% extras, se te dará unos 500 pH</strong> de más gracias a la promoción activada.
				</div>
			{{endif}}
		</div>
		<div class='ipsGrid_span8'>{template="zpaInformation" app="ventas" group="zpa" location="front"}</div>
	</div>
{{endif}}